export const ingredients = [
  { name: "All-purpose cream", brand: "Jersey", price: 52.50, quantity: 250, unit: "ml", daysBeforeCheck: 30 },
  { name: "All-purpose flour", brand: null, price: 65, quantity: 1, unit: "kg", daysBeforeCheck: 25 },
  { name: "Atsuete", brand: null, price: 10, quantity: 40, unit: "g", daysBeforeCheck: 25 },
  { name: "Baguio beans", brand: null, price: 20, quantity: 180, unit: "g", daysBeforeCheck: 20 },
  { name: "Baking powder", brand: "Calumet", price: 18, quantity: 50, unit: "g", daysBeforeCheck: 30 },
  { name: "Banana catsup", brand: "UFC", price: 239.50, quantity: 4, unit: "kg", daysBeforeCheck: 30 },
  { name: "Bawang", brand: null, price: 130, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Bbq powder", brand: "Injoy", price: 30, quantity: 200, unit: "g", daysBeforeCheck: 25 },
  { name: "Beef cube", brand: "Knorr", price: 6.50, quantity: 1, unit: "each", daysBeforeCheck: 50 },
  { name: "Bigas", brand: null, price: 50, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Bihon", brand: "Super Q", price: 40, quantity: 500, unit: "g", daysBeforeCheck: 35 },
  { name: "Bread crumbs", brand: "Happy Fiesta", price: 100, quantity: 1, unit: "kg", daysBeforeCheck: 25 },
  { name: "Burger buns", brand: null, price: 20, quantity: 6, unit: "each", daysBeforeCheck: 40 },
  { name: "Butter", brand: "Butter bar", price: 38, quantity: 200, unit: "g", daysBeforeCheck: 25 },
  { name: "Carrot", brand: null, price: 150, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Celery", brand: null, price: 30, quantity: 120, unit: "g", daysBeforeCheck: 15 },
  { name: "Cheese", brand: "OK", price: 48, quantity: 200, unit: "g", daysBeforeCheck: 20 },
  { name: "Cheese powder", brand: "Injoy", price: 28, quantity: 200, unit: "g", daysBeforeCheck: 25 },
  { name: "Chicharon", brand: null, price: 6, quantity: 20, unit: "g", daysBeforeCheck: 25 },
  { name: "Chicken breast", brand: null, price: 1495, quantity: 6.5, unit: "kg", daysBeforeCheck: 15 },
  { name: "Chicken cube", brand: "Knorr", price: 6.50, quantity: 1, unit: "each", daysBeforeCheck: 50 },
  { name: "Chicken wings", brand: null, price: 1110, quantity: 5.48, unit: "kg", daysBeforeCheck: 15 },
  { name: "Chili flakes", brand: null, price: 22, quantity: 40, unit: "g", daysBeforeCheck: 30 },
  { name: "Chili powder", brand: null, price: 13.25, quantity: 30, unit: "g", daysBeforeCheck: 30 },
  { name: "Condensed", brand: "Jersey", price: 45, quantity: 390, unit: "ml", daysBeforeCheck: 25 },
  { name: "Cornstarch", brand: null, price: 55, quantity: 1, unit: "kg", daysBeforeCheck: 20 },
  { name: "Egg medium", brand: null, price: 200, quantity: 30, unit: "each", daysBeforeCheck: 15 },
  { name: "Egg XS", brand: null, price: 180, quantity: 30, unit: "each", daysBeforeCheck: 15 },
  { name: "Evap", brand: "Healthy Cow", price: 29, quantity: 370, unit: "ml", daysBeforeCheck: 15 },
  { name: "French fries", brand: null, price: 125, quantity: 1, unit: "kg", daysBeforeCheck: 20 },
  { name: "Garlic powder", brand: null, price: 242, quantity: 1, unit: "kg", daysBeforeCheck: 30 },
  { name: "Green peas", brand: "Mega Prime", price: 13.25, quantity: 155, unit: "g", daysBeforeCheck: 30 },
  { name: "Ground beef", brand: "All Time", price: 320, quantity: 1, unit: "kg", daysBeforeCheck: 20 },
  { name: "Ground black pepper", brand: null, price: 150, quantity: 0.25, unit: "kg", daysBeforeCheck: 20 },
  { name: "Ground pork", brand: null, price: 260, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Ham", brand: "All Time", price: 79, quantity: 250, unit: "g", daysBeforeCheck: 25 },
  { name: "Harina", brand: null, price: 45, quantity: 1, unit: "kg", daysBeforeCheck: 20 },
  { name: "Hotdog", brand: "All Time", price: 169, quantity: 30, unit: "each", daysBeforeCheck: 30 },
  { name: "Iced tea", brand: "Pitchel", price: 16, quantity: 20, unit: "g", daysBeforeCheck: 50 },
  { name: "Jelly powder", brand: "Mr Gulaman", price: 14.50, quantity: 25, unit: "g", daysBeforeCheck: 50 },
  { name: "Kalamansi", brand: null, price: 70, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Kamatis", brand: null, price: 80, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Kikiam", brand: "Sea Point", price: 27, quantity: 200, unit: "g", daysBeforeCheck: 30 },
  { name: "Kinchay", brand: null, price: 800, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Liquid seasoning", brand: "Knorr", price: 994.50, quantity: 35, unit: "l", daysBeforeCheck: 25 },
  { name: "Lumpia wrapper medium", brand: null, price: 35, quantity: 45, unit: "each", daysBeforeCheck: 25 },
  { name: "Luncheon meat", brand: "Purefoods", price: 34, quantity: 165, unit: "g", daysBeforeCheck: 20 },
  { name: "Mantika", brand: null, price: 96.1, quantity: 5, unit: "l", daysBeforeCheck: 20 },
  { name: "Mayonnaise", brand: "Best Foods", price: 434.25, quantity: 3.5, unit: "l", daysBeforeCheck: 30 },
  { name: "Molo", brand: "Dinks", price: 25, quantity: 65, unit: "each", daysBeforeCheck: 25 },
  { name: "Mushroom P&S", brand: "Jolly", price: 33, quantity: 198, unit: "g", daysBeforeCheck: 30 },
  { name: "Orange juice", brand: "Pitchel", price: 15, quantity: 19, unit: "g", daysBeforeCheck: 30 },
  { name: "Oregano powder", brand: null, price: 88, quantity: 23, unit: "g", daysBeforeCheck: 30 },
  { name: "Oyster sauce", brand: "Mama Sita", price: 168.70, quantity: 765, unit: "g", daysBeforeCheck: 25 },
  { name: "Palabok pasta", brand: "Super Q", price: 40, quantity: 500, unit: "g", daysBeforeCheck: 25 },
  { name: "Palamig powder", brand: "Tasty", price: 103, quantity: 500, unit: "g", daysBeforeCheck: 30 },
  { name: "Paprika", brand: "Mc Cody", price: 322, quantity: 1, unit: "kg", daysBeforeCheck: 30 },
  { name: "Pasas", brand: null, price: 40, quantity: 250, unit: "g", daysBeforeCheck: 30 },
  { name: "Pipino", brand: null, price: 100, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Porkchop", brand: null, price: 260, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Pork cube", brand: "Knorr", price: 6.50, quantity: 1, unit: "each", daysBeforeCheck: 50 },
  { name: "Pork tapa", brand: null, price: 260, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Repolyo", brand: null, price: 15, quantity: 275, unit: "g", daysBeforeCheck: 15 },
  { name: "Saging saba", brand: null, price: 50, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Salt iodized", brand: null, price: 50, quantity: 3.66, unit: "cup", daysBeforeCheck: 50 },
  { name: "Salt rock", brand: null, price: 25, quantity: 1, unit: "kg", daysBeforeCheck: 50 },
  { name: "Sayote", brand: null, price: 52, quantity: 450, unit: "g", daysBeforeCheck: 15 },
  { name: "Sesame oil", brand: "Lee Kum Kee", price: 161, quantity: 207, unit: "ml", daysBeforeCheck: 25 },
  { name: "Shrimp cube", brand: null, price: 6.50, quantity: 1, unit: "each", daysBeforeCheck: 50 },
  { name: "Sibuyas", brand: null, price: 130, quantity: 1, unit: "kg", daysBeforeCheck: 15 },
  { name: "Sili", brand: null, price: 30, quantity: 75, unit: "g", daysBeforeCheck: 15 },
  { name: "Sour cream powder", brand: "Injoy", price: 32, quantity: 200, unit: "g", daysBeforeCheck: 25 },
  { name: "Spaghetti sauce filipino style", brand: "Del Monte", price: 90, quantity: 900, unit: "g", daysBeforeCheck: 25 },
  { name: "Spring onions", brand: null, price: 15, quantity: 40, unit: "g", daysBeforeCheck: 30 },
  { name: "Sugar brown", brand: null, price: 80.85, quantity: 1, unit: "kg", daysBeforeCheck: 20 },
  { name: "Sugar white", brand: null, price: 93, quantity: 1, unit: "kg", daysBeforeCheck: 20 },
  { name: "Tinapa flakes", brand: null, price: 105, quantity: 1, unit: "kg", daysBeforeCheck: 365 },
  { name: "Toyo", brand: "Datu Puti", price: 191, quantity: 1, unit: "gal", daysBeforeCheck: 30 },
  { name: "Vetsin", brand: "Ajinomoto", price: 62.10, quantity: 250, unit: "g", daysBeforeCheck: 30 },
  { name: "Vinegar", brand: "Datu Puti", price: 6, quantity: 100, unit: "ml", daysBeforeCheck: 30 },
  { name: "Worcestershire sauce", brand: "Del Society", price: 20, quantity: 5, unit: "fl-oz", daysBeforeCheck: 30 }
];
